metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: true


metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: docker
  metricsets:
    - container
    - cpu
    - diskio
    - healthcheck
    - info
    #- image
    - memory
    - network
  hosts: ['unix:///var/run/docker.sock']
  period: 10s
  enabled: true

# Module: rabbitmq
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.x/metricbeat-module-rabbitmq.html

- module: rabbitmq
  metricsets: ["node", "queue", "connection"]
  enabled: true
  period: 10s
  hosts: "rabbitmq:5672"
  username: guest
  password: guest
 

#- module: logstash
#  metricsets:
#    - node
#    - node_stats
#  period: 10s
#  hosts: ['localhost:9600']
#  username: "elastic"
#  password: "changeme"


processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["http://${ELASTICSEARCH_HOST_PORT}"]
  username: ${ELASTIC_USERNAME}
  password: ${ELASTIC_PASSWORD}

setup.kibana:
  host: "http://kibana:5601"
  username:  ${ELASTIC_USERNAME}
  password: ${ELASTIC_PASSWORD}

setup.dashboards.always_kibana: true #Only talk to Kibana, which is important for the retry
setup.dashboards.retry.enabled: true
setup.dashboards.enabled: true

http.enabled: true
http.host: 0.0.0.0