version: '2'
services:

  rabbitmq:
    restart: always
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rmq

networks:
  rmq: